logging:
  level:
    org.springframework.ws: TRACE
    org.apache.http: DEBUG
base:
  url: http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso?WSDL
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: lyukutan
    url: jdbc:h2:mem:testdb
    username: lyukutan
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none